TARGETS=basic-lifecycle disabled-module-unload enabled-save-on-restart

all: $(TARGETS)

basic-lifecycle:
	(cd $@ && make)
disabled-module-unload:
	(cd $@ && make)
enabled-save-on-restart:
	(cd $@ && make)

.PHONY: $(TARGETS)
